### ISSUE TITLE
print/validate MADSIM_CONFIG_HASH

### ISSUE THREAD

**Issue by xxchan** [madsim-rs/madsim#123]
I see this line in the output, but it seems this hash is nowhere printed and valiadated 😄

```
and make sure `MADSIM_CONFIG_HASH=1AD2E4ABC41F3553`
```

**Comment by wangrunji0408** [comment]
This line is printed from the `madsim-macros` crate. The initial purpose is a hint for users to check it manually and make sure they are the same across multiple runs, otherwise the result would not be reproducible if the configuration were changed. It was designed to have a configuration file as an input of the simulation. However, this mechanism has never been used later. So I'm considering removing this line to prevent further confusion. What do you think? 😄
